//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaraPhotographyAssociation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysParam
    {
        public int Id { get; set; }
        public string ParaName { get; set; }
        public string ParaVal { get; set; }
    }
}
